version: "3"

services:
  # create node 1
  api:
    image: lb_go:latest
    ports:
      - "3000:3000"
    restart: "always"
    command: ["./main" , "3000" , "api-1"]
    networks:
      - "api.network"
# Create node 2
  api2:
    image: lb_go:latest
    ports:
      - "5000:5000"
    restart: "always"
    command: ["./main" , "5000" , "api-2"]
    networks:
      - "api.network"
# Pull nginx images
  nginx:
    image: nginx:latest
    ports:
    - "4000:4000"
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
         - "api.network"
networks:
  api.network: